version: 2
jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      SCRATCH: "/scratch"
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/src/xcpEngine
    steps:
      - run:
          name: Install parallel gzip and python3
          command: |
            apk add --no-cache pigz python3
      - restore_cache:
          keys:
            - docker-v1-{{ .Branch }}-{{ epoch }}
            - docker-v1-{{ .Branch }}-
            - docker-v1-master-
            - docker-v1-
          paths:
            - /tmp/cache/docker.tar.gz
            - /tmp/cache/ubuntu.tar.gz
      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Build Docker image
          no_output_timeout: 60m
          command: |
            # Get version, update files.
            THISVERSION=$( python3 about/get_version.py )
            if [[ ${THISVERSION:0:1} == "0" ]] ; then
              echo "WARNING: latest git tag could not be found"
              echo "Please, make sure you fetch all tags from upstream with"
              echo "the command ``git fetch --tags --verbose`` and push"
              echo "them to your fork with ``git push origin --tags``"
            fi
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=pennbbl/xcpengine \
                --rm=false \
                -t pennbbl/xcpengine:latest \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]

      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save pennbbl/baseimages:common pennbbl/xcpengine:latest \
            | pigz -8 -p 3 > /tmp/cache/docker.tar.gz

      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/docker.tar.gz
            - src/xcpEngine

  get_data:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /home/circleci/data
    steps:
      - restore_cache:
          keys:
            - data-v1-{{ epoch }}
            - data-v1-
      - run:
          name: Get test data from box
          command: |
            mkdir -p /tmp/data
            if [[ ! -d /tmp/data/downsampled ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O downsampled.tar.xz "https://upenn.box.com/shared/static/34gjb9nlm8toouh42fgwip2mpvm5ofg7.xz"
              tar xvfJ downsampled.tar.xz -C /tmp/data/
            else
              echo "Dataset downsampled data was cached"
            fi
            # Prepare a cohort for the anatomical test
            echo "id0,img" > anat_cohort.csv
            echo "sub-1,/anat/sub-1_desc-preproc_T1w.nii.gz" >> anat_cohort.csv
            # Prepare MNI-space BOLD
            echo "id0,img" > mni_bold_cohort.csv
            echo "sub-1,/func/sub-1_task-rest_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz" >> mni_bold_cohort.csv
            # Prepare T1w space BOLD
            echo "id0,img" > t1_bold_cohort.csv
            echo "sub-1,/func/sub-1_task-rest_space-T1w_desc-preproc_bold.nii.gz" >> t1_bold_cohort.csv

      - persist_to_workspace:
          root: /tmp
          paths:
            - data
      - save_cache:
         key: data-v1-{{ epoch }}
         paths:
            - /tmp/data

  t1fc36p:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/data
    steps:
      - checkout:
          path: /home/circleci/src/xcpengine
      - run:
          name: Check whether build should be skipped
          command: |
            cd /home/circleci/src/qsiprep
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?t1fc36p\]' )" != "" ]]; then
              echo "Skipping t1fc36p build"
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - t1fc36p-anat-v1-{{ .Branch }}-{{ epoch }}
            - t1fc36p-anat-v1-{{ .Branch }}
            - t1fc36p-anat-v1-master
            - t1fc36p-anat-v1-
      - run:
          name: Setting up test
          command: |
            mkdir -p /tmp/t1fc36p/xcpOutput && sudo setfacl -d -m group:$(id -gn):rwx /tmp/t1fc36p/xcpOutput && sudo setfacl -m group:$(id -gn):rwx /tmp/t1fc36p/xcpOutput
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi

      - run:
          name: Run full xcpengine on t1fc36p bold
          no_output_timeout: 2h
          command: |
            sudo setfacl -d -m group:$(id -gn):rwx /tmp/t1fc36p/xcpOutput && \
                sudo setfacl -m group:$(id -gn):rwx /tmp/t1fc36p/xcpOutput
            sudo setfacl -d -m group:$(id -gn):rwx /tmp/t1fc36p/work && \
                sudo setfacl -m group:$(id -gn):rwx /tmp/t1fc36p/work

            docker run --rm -it pennbbl/xcpengine:latest \
                -d /home/circleci/src/xcpengine/designs/fc-36p.dsn \
                -c /tmp/data/t1_bold_cohort.csv \
                -o /tmp/t1fc36p/xcpOutput \
                -i /tmp/t1fc36p/work \
                -m s \
                -r /tmp/data/downsampled

      - run:
          name: Checking outputs of fc36p
          command: |
            mkdir -p /tmp/t1fc36p/test
            find /tmp/t1fc36p/xcpOutput -path */figures -prune -o -name "*" -print | sed s+/tmp/t1fc36p/xcpOutput/++ | sort > /tmp/t1fc36p/test/outputs.out
            diff /tmp/src/xcpengine/.circleci/t1fc36p_outputs.txt /tmp/t1fc36p/test/outputs.out
            exit $?

      - run:
          name: Clean working directory
          when: always
          command: |
            sudo chown $(id -un):$(id -gn) -R /tmp/t1fc36p
            find /tmp/t1fc36p/work -not -name "*.svg" -not -name "*.html" -not -name "*.rst" \
                -not -name "*.mat" -not -name "*.lta" -not -name "*.json" -not -name "*.txt" -not -name "*.pklz" -type f -delete
            find /tmp/t1fc36p/work_partial -not -name "*.svg" -not -name "*.html" -not -name "*.rst" \
                -not -name "*.mat" -not -name "*.lta" -not -name "*.json" -not -name "*.txt" -not -name "*.pklz" -type f -delete

      - store_artifacts:
          path: /tmp/t1fc36p

  update_cache:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /tmp/src/xcpEngine
    steps:
      - attach_workspace:
          at: /tmp
      - save_cache:
         key: docker-v1-{{ .Branch }}-{{ epoch }}
         paths:
            - /tmp/cache/docker.tar.gz


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - get_data:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - update_cache:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
            tags:
              only: /.*/

      - t1fc36p:
          requires:
            - get_data
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
                - /ds054\/.*/
                - /ds210\/.*/
            tags:
              only: /.*/

      - mni_pipeline:
          requires:
            - get_data
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
                - /tests?\/.*/
                - /ds054\/.*/
                - /ds210\/.*/
            tags:
              only: /.*/

      - deploy_docker:
          requires:
            - build
            - t1fc36p
          filters:
            branches:
              only: master
            tags:
              only: /.*/
